name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  nixfmt:
    name: nixfmt
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: check formatting
        run: nix fmt -- --ci
